baseURL = "https://broch.tech/"
languageCode = "en-gb"
title = "broch.tech"
sectionPagesMenu = "main"

[params]
  description = "Programming (often in Haskell and Elm), identity management, OpenID, security, Linux, other things."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences=false

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"
